env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - "plugin:react/recommended"
  - "airbnb"
  - "airbnb/hooks"
  - "prettier"
  - "prettier/babel"
  - "prettier/flowtype"
  - "prettier/react"
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:jest/recommended"
  - "plugin:jest/style"
  - "plugin:jsx-a11y/recommended"
  - "plugin:react-hooks/recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
    tsx: true
  ecmaVersion: 12
  sourceType: module
parser: "@typescript-eslint/parser"
plugins:
  - "react"
  - "react-hooks"
  - "import"
  - "eslint-plugin-import-helpers"
  - "jest"
  - "jsx-a11y"
  - "@emotion"
rules: {
    radix: "error",
    no-self-compare: "error",
    "@emotion/jsx-import": "error",
    "@emotion/no-vanilla": "error",
    "@emotion/import-from-emotion": "error",
    "@emotion/styled-import": "error",
    no-alert: 'off',
		no-console: 'off',
    no-throw-literal: 'off',
    import/prefer-default-export: "off",
    import/prefer-default-import: "off",
    no-confusing-arrow: "error",
    import/no-default-export: "off",
    no-compare-neg-zero: "error",

    no-unused-vars: "off",
    no-dupe-else-if: "error",
    react/destructuring-assignment: "off",
    react/jsx-props-no-spreading: "off",
    no-irregular-whitespace: ["error", { skipTemplates: true }],
    array-callback-return: "error",
    operator-linebreak: [2, "before", { overrides: { "?": "after" } }],
    block-scoped-var: "error",
    react/prop-types: "off",
    eqeqeq: ["error", "always"],
    implicit-arrow-linebreak: ["error", "beside"],
    no-use-before-define: "off",
    max-len:
      [
        "error",
        100,
        2,
        {
          ignoreUrls: true,
          ignoreComments: false,
          ignoreRegExpLiterals: true,
          ignoreStrings: false,
          ignoreTemplateLiterals: false,
        },
      ],
    object-curly-newline: ["error", { consistent: true }],
    newline-per-chained-call: ["error", { ignoreChainWithDepth: 2 }],
    complexity: ["warn", { max: 50 }],
    indent: [2, "tab"],
    treatUndefinedAsUnspecified: "off",
    class-methods-use-this: "off",
    react/jsx-curly-newline: "off",
    react/jsx-filename-extension:
      [1, { extensions: [".jsx", ".tsx", ".js", ".ts"] }],
    no-param-reassing: "off",
    no-underscore-dangle: "off",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "error",
    react/jsx-indent: [2, "tab"],
    import/no-extraneous-dependencies: ["off", { devDependencies: true }],
    # import/extensions: '[ 'error', 'ignorePackages', { ts: 'never', tsx: 'never' } ]',
    import/extensions: "off",
    lines-around-comment:
      [
        "error",
        {
          "beforeBlockComment": true,
          "afterBlockComment": false,
          "beforeLineComment": true,
          "afterLineComment": false,
          "allowBlockStart": true,
          "allowBlockEnd": true,
          "allowObjectStart": true,
          "allowObjectEnd": true,
          "allowArrayStart": true,
          "allowArrayEnd": true,
        },
      ],
    eslint-import-resolver-node: "off",
    no-mixed-operators: "error",
    no-unexpected-multiline: "error",
    quotes: ["error", "backtick"],
    import/no-unresolved: "off",
    import/named: 1,
    import/namespace: 1,
    import/default: 1,
    import/export: 1,
    import/no-useless-path-segments: 1,
    semi: "error",
    import-helpers/order-imports:
      ["warn", { newlinesBetween: "always", groups: [
              "module",
              "/^@shared/",
              ["parent", "sibling", "index"],
              /^
              (assert
              |async_hooks
              |buffer
              |child_process
              |cluster
              |console
              |constants
              |crypto
              |dgram
              |dns
              |domain
              |events
              |fs
              |http
              |http2
              |https
              |inspector
              |module
              |net
              |os
              |path
              |perf_hooks
              |process
              |punycode
              |querystring
              |readline
              |repl
              |stream
              |string_decoder
              |timers
              |tls
              |trace_events
              |tty
              |url
              |util
              |v8
              |vm
              |zli
              )/,
            ], alphabetize: { order: "asc", ignoreCase: true } }],
    jest/no-disabled-tests: "warn",
    jest/no-focused-tests: "error",
    jest/no-identical-title: "error",
    jest/prefer-to-have-length: "warn",
    jest/valid-expect: "error",
    jsx-a11y/rule-name: "off",
  }
settings:
  react:
    version: "detect"
  import/extensions: [".js", ".ts", ".jsx", ".tsx"]
  import/resolver: { node: { extensions: [".js", ".jsx"] } }
  jest:
    version: "detect"
